version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    command: sh -c "cd code/src/backend && flask run --host=0.0.0.0 --port 5001"